import "server-only";

import { randomBytes } from "node:crypto";
import { ApiError } from "@/lib/api/errors";
import { query, toDate, SQL_NOW } from "@/lib/db/client";
import type { WebhookDelivery, WebhookEvent, WebhookRecord } from "@/types/webhook";

function serialize(row: Record<string, unknown>): WebhookRecord {
  return { id: String(row.id), name: String(row.name ?? ""), url: String(row.url ?? ""), events: Array.isArray(row.events) ? row.events as WebhookEvent[] : [], enabled: Boolean(row.enabled), lastTriggeredAt: toDate(row.last_triggered_at)?.toISOString() ?? null, lastStatus: row.last_status === "success" || row.last_status === "failed" ? row.last_status : null, failureCount: Number(row.failure_count ?? 0), createdAt: toDate(row.created_at)?.toISOString() ?? new Date(0).toISOString(), updatedAt: toDate(row.updated_at)?.toISOString() ?? new Date(0).toISOString(), createdBy: String(row.created_by ?? "") };
}

export async function listWebhooks(): Promise<WebhookRecord[]> { const result = await query(`SELECT id, name, url, events, enabled, last_triggered_at, last_status, failure_count, created_at, updated_at, created_by FROM webhooks ORDER BY created_at DESC`); return result.rows.map(serialize); }
export async function createWebhook(input: { name: string; url: string; events: WebhookEvent[]; createdBy: string }): Promise<{ webhook: WebhookRecord; secret: string }> {
  const secret = `whsec_${randomBytes(24).toString("base64url")}`; const result = await query(`INSERT INTO webhooks(name, url, events, secret, created_by) VALUES ($1,$2,$3,$4,$5) RETURNING id, name, url, events, enabled, last_triggered_at, last_status, failure_count, created_at, updated_at, created_by`, [input.name.trim().slice(0, 80), input.url.trim(), input.events, secret, input.createdBy]); return { webhook: serialize(result.rows[0]), secret };
}
export async function updateWebhook(id: string, patch: { name?: string; url?: string; events?: WebhookEvent[]; enabled?: boolean }): Promise<WebhookRecord> { const result = await query(`UPDATE webhooks SET name = COALESCE($2,name), url = COALESCE($3,url), events = COALESCE($4,events), enabled = COALESCE($5,enabled), failure_count = CASE WHEN $5 = true THEN 0 ELSE failure_count END, updated_at = ${SQL_NOW} WHERE id = $1 RETURNING id, name, url, events, enabled, last_triggered_at, last_status, failure_count, created_at, updated_at, created_by`, [id, patch.name?.trim().slice(0,80) || null, patch.url?.trim() || null, patch.events ?? null, patch.enabled ?? null]); if (!result.rows[0]) throw new ApiError(404, "WEBHOOK_NOT_FOUND", "The webhook was not found."); return serialize(result.rows[0]); }
export async function deleteWebhook(id: string): Promise<void> { await query(`DELETE FROM webhooks WHERE id = $1`, [id]); }
export async function rotateWebhookSecret(id: string): Promise<string> { const secret = `whsec_${randomBytes(24).toString("base64url")}`; const result = await query(`UPDATE webhooks SET secret = $2, updated_at = ${SQL_NOW} WHERE id = $1 RETURNING id`, [id, secret]); if (!result.rowCount) throw new ApiError(404, "WEBHOOK_NOT_FOUND", "The webhook was not found."); return secret; }
export async function getWebhookWithSecret(id: string): Promise<DispatchableWebhook | null> { const result = await query(`SELECT id, url, secret FROM webhooks WHERE id = $1 AND enabled = true`, [id]); const row = result.rows[0]; return row ? { id: String(row.id), url: String(row.url), secret: String(row.secret) } : null; }
export async function recordDelivery(input: { webhookId: string; event: WebhookEvent; status: "success" | "failed"; statusCode: number | null; durationMs: number; error: string | null }): Promise<void> { await query(`INSERT INTO webhook_deliveries(webhook_id,event,status,status_code,duration_ms,error) VALUES ($1,$2,$3,$4,$5,$6)`, [input.webhookId,input.event,input.status,input.statusCode,input.durationMs,input.error]); await query(`UPDATE webhooks SET last_triggered_at=${SQL_NOW}, last_status=$2, failure_count=CASE WHEN $2='failed' THEN failure_count+1 ELSE 0 END, enabled=CASE WHEN $2='failed' AND failure_count+1 >= 20 THEN false ELSE enabled END, updated_at=${SQL_NOW} WHERE id=$1`, [input.webhookId,input.status]); }
export async function listDeliveries(webhookId: string, limit = 50): Promise<WebhookDelivery[]> { const result = await query(`SELECT id, webhook_id, event, status, status_code, duration_ms, error, created_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY created_at DESC LIMIT $2`, [webhookId, Math.min(Math.max(limit,1),100)]); return result.rows.map((row) => ({ id: String(row.id), webhookId: String(row.webhook_id), event: row.event as WebhookEvent, status: row.status as "success" | "failed", statusCode: typeof row.status_code === "number" ? row.status_code : null, durationMs: Number(row.duration_ms ?? 0), error: typeof row.error === "string" ? row.error : null, createdAt: toDate(row.created_at)?.toISOString() ?? new Date(0).toISOString() })); }
export interface DispatchableWebhook { id: string; url: string; secret: string; }
export async function getWebhooksForEvent(event: WebhookEvent): Promise<DispatchableWebhook[]> { const result = await query(`SELECT id, url, secret FROM webhooks WHERE enabled = true AND EXISTS (SELECT 1 FROM json_each(webhooks.events) WHERE json_each.value = $1)`, [event]); return result.rows.map((row) => ({ id: String(row.id), url: String(row.url), secret: String(row.secret) })).filter((webhook) => Boolean(webhook.url && webhook.secret)); }
