"use client";

import { useEffect, useState } from "react";
import { LoaderCircle, Save, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Notice } from "@/components/ui/notice";
import { PageLoading } from "@/components/ui/loading";
import { apiFetch, ClientApiError } from "@/lib/client/api";
import type { SerializedSettings } from "@/types/settings";
import { retentionLabel } from "@/utils/format";

type FormState = Omit<SerializedSettings, "updatedAt" | "updatedBy"> & { applyToExisting: boolean };

function toState(settings: SerializedSettings): FormState { return { ...settings, applyToExisting: false }; }

export function SettingsForm() {
  const [form, setForm] = useState<FormState | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error" | "warning"; text: string } | null>(null);
  useEffect(() => { apiFetch<{ settings: SerializedSettings }>("/api/settings").then(({ settings }) => setForm(toState(settings))).catch((caught) => setMessage({ type: "error", text: caught instanceof ClientApiError ? caught.message : "Settings are unavailable." })); }, []);
  function set<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => current ? { ...current, [key]: value } : current); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!form || busy) return; setBusy(true); setMessage(null); try { const { settings, updatedFiles } = await apiFetch<{ settings: SerializedSettings; updatedFiles: number }>("/api/settings", { method: "PATCH", body: JSON.stringify(form) }); setForm(toState(settings)); setMessage({ type: "success", text: updatedFiles ? `Settings saved. The selected default retention was applied to ${updatedFiles} active document${updatedFiles === 1 ? "" : "s"}.` : "Settings saved. Existing documents were not changed." }); } catch (caught) { setMessage({ type: "error", text: caught instanceof ClientApiError ? caught.message : "Settings could not be saved." }); } finally { setBusy(false); } }
  if (!form) return message?.type === "error" ? <Notice type="error">{message.text}</Notice> : <PageLoading label="Loading storage settings" />;
  const sizeMb = Math.round(form.maxPdfSizeBytes / 1024 / 1024);
  const limitGb = Number((form.storageLimitBytes / 1024 / 1024 / 1024).toFixed(1));
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-ngo-600">Administration</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-ink-900 sm:text-3xl">Storage settings</h1><p className="mt-2 text-sm text-slate-600">Defaults apply to new documents. Every change is audited.</p></header><form className="space-y-6" onSubmit={save}>{message && <Notice type={message.type}>{message.text}</Notice>}<section className="panel p-5 sm:p-6"><h2 className="font-bold text-ink-900">Capacity and access links</h2><p className="mt-1 text-sm text-slate-600">Limits are enforced server-side before an R2 upload URL is issued.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><NumberField label="Maximum document size (MB)" value={sizeMb} min={1} max={500} disabled={busy} onChange={(value) => set("maxPdfSizeBytes", value * 1024 * 1024)} /><NumberField label="Configured storage limit (GB)" value={limitGb} min={1} max={1024} step={0.5} disabled={busy} onChange={(value) => set("storageLimitBytes", Math.round(value * 1024 * 1024 * 1024))} /><NumberField label="Signed URL expiry (seconds)" value={form.signedUrlExpirySeconds} min={60} max={3600} disabled={busy} onChange={(value) => set("signedUrlExpirySeconds", value)} /><div><label className="field-label" htmlFor="default-retention">Default retention</label><select id="default-retention" className="field-input" disabled={busy} value={form.defaultRetentionType} onChange={(event) => set("defaultRetentionType", event.target.value as FormState["defaultRetentionType"])}>{(["never", "30_days", "3_months", "6_months", "1_year"] as const).map((type) => <option key={type} value={type}>{retentionLabel(type)}</option>)}</select></div></div></section>
    <section className="panel p-5 sm:p-6"><h2 className="font-bold text-ink-900">Automatic deletion safety</h2><p className="mt-1 text-sm text-slate-600">The recommended configuration moves due files to Trash before their private object is permanently deleted.</p><div className="mt-5 space-y-4"><Toggle label="Default automatic deletion" description="New documents inherit this choice unless the uploader selects a different retention policy." checked={form.defaultAutoDelete} disabled={busy} onChange={(value) => set("defaultAutoDelete", value)} /><Toggle label="Move automatically deleted documents to Trash first" description="Keep this enabled to make automatic deletion recoverable. Disabling it causes due documents to be permanently deleted by cleanup." checked={form.trashEnabled} disabled={busy} danger={!form.trashEnabled} onChange={(value) => set("trashEnabled", value)} /><NumberField label="Trash retention (days)" value={form.trashRetentionDays} min={1} max={365} disabled={busy} onChange={(value) => set("trashRetentionDays", value)} /></div></section>
    <section className="panel p-5 sm:p-6"><h2 className="font-bold text-ink-900">Storage warnings</h2><p className="mt-1 text-sm text-slate-600">Warnings use text and icons in addition to color so capacity status is understandable to everyone.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><NumberField label="Warning threshold (%)" value={form.warningThresholdPercent} min={1} max={98} disabled={busy} onChange={(value) => set("warningThresholdPercent", value)} /><NumberField label="Critical threshold (%)" value={form.criticalThresholdPercent} min={2} max={99} disabled={busy} onChange={(value) => set("criticalThresholdPercent", value)} /></div></section>
    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-800" /><div><h2 className="font-bold text-amber-950">Apply default retention to existing documents</h2><p className="mt-1 text-sm leading-6 text-amber-900">This is optional. Leaving it unchecked preserves the retention on every existing active document. If selected, server-side dates are recalculated from now and the action is recorded in the audit log.</p><label className="mt-4 flex items-center gap-3 text-sm font-semibold text-amber-950"><input type="checkbox" className="h-4 w-4 rounded border-amber-400 text-ngo-600" checked={form.applyToExisting} onChange={(event) => set("applyToExisting", event.target.checked)} disabled={busy} />Apply to existing active documents</label></div></div></section>
    <div className="flex justify-end"><Button type="submit" disabled={busy}>{busy ? <><LoaderCircle className="h-4 w-4 animate-spin" />Saving settings…</> : <><Save className="h-4 w-4" />Save settings</>}</Button></div></form></div>;
}

function NumberField({ label, value, min, max, step = 1, disabled, onChange }: { label: string; value: number; min: number; max: number; step?: number; disabled: boolean; onChange: (value: number) => void }) { const id = label.toLowerCase().replace(/[^a-z]+/g, "-"); return <div><label className="field-label" htmlFor={id}>{label}</label><input id={id} type="number" className="field-input" min={min} max={max} step={step} value={value} disabled={disabled} onChange={(event) => { const number = Number(event.target.value); if (Number.isFinite(number)) onChange(number); }} /></div>; }
function Toggle({ label, description, checked, disabled, onChange, danger = false }: { label: string; description: string; checked: boolean; disabled: boolean; onChange: (value: boolean) => void; danger?: boolean }) { return <label className={`flex items-start gap-3 rounded-xl border p-4 ${danger ? "border-red-200 bg-red-50" : "border-slate-200"}`}><input type="checkbox" className="mt-1 h-4 w-4 rounded border-slate-300 text-ngo-600" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span><strong className={danger ? "text-red-950" : "text-ink-900"}>{label}</strong><span className={danger ? "mt-0.5 block text-sm text-red-800" : "mt-0.5 block text-sm text-slate-600"}>{description}</span></span></label>; }
